# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biz',
            name='offer',
            field=models.ManyToManyField(blank=True, null=True, to='api.Offer'),
        ),
        migrations.AlterField(
            model_name='biz',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='api.Photos'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='api.Photos'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='api.Photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.ManyToManyField(blank=True, null=True, to='api.Hobby'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='api.Photos'),
        ),
    ]
