# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160928_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='photos',
        ),
        migrations.AddField(
            model_name='offer',
            name='green_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Photos'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_after_discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_before_discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='red_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='biz',
            name='offer',
            field=models.ManyToManyField(to='api.Offer'),
        ),
        migrations.AlterField(
            model_name='biz',
            name='photos',
            field=models.ManyToManyField(to='api.Photos'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='photos',
            field=models.ManyToManyField(to='api.Photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.ManyToManyField(to='api.Hobby'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photos',
            field=models.ManyToManyField(to='api.Photos'),
        ),
    ]
